### ISSUE TITLE
Not compatible with ESP8266

### ISSUE THREAD

**Issue by rakshithbk** [moderndevice/CapSense#1]
Compilation results in error --
`error: cannot convert 'volatile uint32_t* {aka volatile unsigned int*}' to 'volatile uint8_t* {aka volatile unsigned char*}' in assignment
  rReg = portModeRegister(rPort);`

The error is same for all `portModeRegistor()` statements in the library.

**Comment by moderndevice** [comment]
rakshithbk,

You might see if the fork that   Paul Stoffregen is maintaining has compile options for the ESP8266

Paul

**Comment by rakshithbk** [comment]
Thank you [Paul Stoffregen](https://github.com/PaulStoffregen/CapacitiveSensor) fork worked..!
